export const ErrorCode = Object.freeze({
  AUTH_INVALID_USERNAME_OR_PASSWORD: "AUTH_INVALID_USERNAME_OR_PASSWORD",
  AUTH_ACCOUNT_IS_LOCKED_OUT: "AUTH_ACCOUNT_IS_LOCKED_OUT",
  AUTH_EMAIL_NOT_CONFIRMED: "AUTH_EMAIL_NOT_CONFIRMED",
});
